describe: > 
 test sidd validation with nafnet-sidd
name: nafnet-sidd
output_path: ./outputs/val
epochs: 100
val_check_interval: 1.0
model:
  name: mmpn
  params: 
    pd_train: 5
    pd_val: 2
    dn_net: mmbd
    r3: 0.16
    net_param:
      branch_num: 1
      dn_branch: NAFNetBase
      branches_order: [0, 0]
      net_param:
        img_channel: 3
        width: 32
        enc_blk_nums: [2, 2, 4, 8]
        middle_blk_num: 12
        dec_blk_nums: [2, 2, 2, 2]
        dw_expand: 1
        ffn_expand: 2
  checkpoint_path: weights/nafnet-sidd-val_avg_psnr=36.94.ckpt

test:
  type: SIDD_validation
  dataset:
    sidd_val_dir: /mnt/f/datasets/SIDD
    len: 1280
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 6


