describe: > 
 test sidd validation with restormer
name: restormer-sidd
output_path: ./outputs/val
epochs: 100
val_check_interval: 1.0
model:
  name: mmpn
  params: 
    pd_train: 5
    pd_val: 2
    dn_net: mmbd
    r3: 0.16
    net_param:
      branch_num: 1
      dn_branch: Restormer
      branches_order: [0,0]
      net_param:
        inp_channels: 3
        out_channels: 3
        dim: 48
        num_blocks: [4,6,6,8]
        num_refinement_blocks: 4
        heads: [1,2,4,8]
        ffn_expansion_factor: 2.66
        bias: False
        LayerNorm_type: 'BiasFree'
        dual_pixel_task: False
  checkpoint_path: weights/restormer-sidd-val_avg_psnr=37.92.ckpt

test:
  type: SIDD_validation
  dataset:
    sidd_val_dir: /mnt/f/datasets/SIDD
    len: 1280
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 6


