describe: > 
 train with deamnet as denoiser
name: deamnet-sidd
output_path: ./outputs/train
epochs: 100
val_check_interval: 0.1
model:
  name: mmpn
  params: 
    pd_train: 5
    pd_val: 2
    dn_net: mmbd
    r3: 0.
    net_param:
        branch_num: 1
        dn_branch: Deam
        branches_order: [0, 0]
        net_param:
          Isreal: true
  checkpoint_path: weights/deamnet-sidd-val_avg_psnr=37.80.ckpt
  optimizer:
    opt: Adamw
    lr: !!float 1e-4
    betas: [0.9, 0.999]
    weight_decay: 0
    momentum: 0.9

loss:
  name: FirstPdMaskLoss
  param:
    loss_type: l1
    pd_factor: 5

train:
  type: UnpairDataset
  dataset:
    path: datasets/lmdb/medium_512_512_lmdb
    datatype: lmdb
    max_len: 10000
    crop_size: 160
    augment: True
  dataloader:
    batch_size: 8
    shuffle: true
    num_workers: 6
val:
  type: SIDD_validation
  dataset:
    sidd_val_dir: datasets/SIDD_MAT
    len: 128
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 6